name: cuidapet_my_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.4.0
  crypto: ^3.0.5
  dotenv: ^4.2.0
  get_it: ^7.7.0
  http: ^1.2.2
  injectable: ^2.4.4
  jaguar_jwt: ^3.0.0
  logger: ^2.4.0
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  lints: ^4.0.0
  shelf_router_generator: ^1.1.0
  test: ^1.24.0

